### ISSUE TITLE
Goroutine leaking

### ISSUE THREAD

**Issue by tie** [mbobakov/grpc-consul-resolver#9]
Service query loop in `watchConsulService` is not terminated on `ctx.Done()`.

https://github.com/mbobakov/grpc-consul-resolver/blob/5a2eeec5e02d178621087cf6f219065ac09b3ac9/consul.go#L79-L90

The fix is shown in [A Tour of Go: Concurrency](https://tour.golang.org/concurrency/5).

```go
res := make(chan []string)
quit := make(chan struct{})
```

```go
		select {
		case res <- ee:
			continue
		case <-quit:
			return
		}
	}
}()
  
for {
	select {
	case ee := <-res:
		out <- ee
	case <-ctx.Done():
		close(quit)
		return
	}
}
```

**Comment by mbobakov** [comment]
@tie Good catch. Thanks. I'll check and fix.

**Comment by philippgille** [comment]
Closing `res` can lead to a panic in the goroutine.

From the [tour page you linked to](https://tour.golang.org/concurrency/5):

> A select blocks until one of its cases can run, then it executes that case. It chooses one at random if multiple are ready. 

So if there's an `ee` result and `quit` is closed, it chooses randomly, and if it selects the `<- ee` one, but `res` is also closed, it will panic.

You can take the [code from the tour page you linked to](https://tour.golang.org/concurrency/5) and adapt it a bit and when running it multiple times, it will lead to a panic sometimes (only sometimes because of the random selection): <https://play.golang.org/p/isJ_jcKPYwg>

I think it's safer to only close `quit`. `res` should then be garbage collected at some point.
